export const LegendaryStaking_ABI = [
  // write
  "function deposit(uint256 amount)",
  "function compoundToPool2(uint256[] posIds, uint256 amount)",
  "function claimInterest(uint256[] posIds)",
  "function withdraw(uint256 posId)",
  "function earlyWithdraw(uint256 posId)",
  "function claimRewards()",
  "function claimTokenRewards() returns (uint256 usdvOut, uint256 fdaoOut)",
  // read
  "function positions(uint256 id) view returns (address user, uint256 principal, uint256 startTime, uint256 lastAccrueTime, uint256 aprBps, uint256 accruedClaimable, uint8 poolType, bool withdrawn)",
  "function getUserPositions(address user) view returns (uint256[])",
  "function pendingInterest(uint256 posId) view returns (uint256)",
  "function referralClaimable(address user) view returns (uint256)",
  "function lastClaimAt(address user) view returns (uint256)",
  "function totalPool1Principal() view returns (uint256)",
  "function totalPool2Principal() view returns (uint256)",
  "function currentDayInflow() view returns (uint256)",
  "function paused() view returns (bool)",
  "function frozen(address user) view returns (bool)",
  "function pool1BaseAprBps() view returns (uint256)",
  "function pool2AprBps() view returns (uint256)",
  "function per5kBonusBps() view returns (uint256)",
  "function maxBonusBps() view returns (uint256)",
  "function bonusUnit() view returns (uint256)",
  "function minDeposit() view returns (uint256)",
  "function minStakeForReferral() view returns (uint256)",
  "function lockDuration() view returns (uint256)",
  "function earlyPenaltyBps() view returns (uint256)",
  "function pendingUsdv(address) view returns (uint256)",
  "function pendingFdao(address) view returns (uint256)",
  "function previewTokenRewards(address) view returns (uint256 usdvInterest, uint256 usdvLevel, uint256 fdaoInterest, uint256 fdaoLevel)",
  "function usdvPerInterestBps() view returns (uint256)",
  "function fdaoPerInterestBps() view returns (uint256)",
  "function maxUsdvLevelReached(address) view returns (uint8)",
  "function maxFdaoLevelReached(address) view returns (uint8)",
  "function getLevelBonusUsdv() view returns (uint256[7])",
  "function getLevelBonusFdao() view returns (uint256[7])",
  "function usdv() view returns (address)",
  "function futureDao() view returns (address)",
  // events
  "event Deposited(address indexed user, uint256 indexed posId, uint8 poolType, uint256 amount, uint256 aprBps)",
  "event InterestClaimed(address indexed user, uint256 amount)",
  "event Withdrawn(address indexed user, uint256 indexed posId, uint256 amount)",
  "event EarlyWithdrawn(address indexed user, uint256 indexed posId, uint256 amount, uint256 penalty)",
  "event ReferralAccrued(address indexed from, address indexed to, uint8 level, uint256 amount)",
  "event DynamicAccrued(address indexed from, address indexed to, uint8 vLevel, uint256 amount)",
  "event RewardsClaimed(address indexed user, uint256 amount)",
  "event UsdvAccrued(address indexed user, uint256 usdtInterest, uint256 usdvAmount)",
  "event FdaoAccrued(address indexed user, uint256 usdtInterest, uint256 fdaoAmount)",
  "event UsdvClaimed(address indexed user, uint256 fromInterest, uint256 fromLevel, uint8 levelFrom, uint8 levelTo)",
  "event FdaoClaimed(address indexed user, uint256 fromInterest, uint256 fromLevel, uint8 levelFrom, uint8 levelTo)",
] as const;
