// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-latest-news.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_latest_news_default = defineTool({
  name: "get_latest_news",
  title: "Get latest announcements",
  description: "Fetch the most recent USD.ONLINE announcements/news items published to the platform.",
  inputSchema: {
    limit: z.number().int().min(1).max(20).default(5).describe("Number of most recent announcements to return (1-20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("announcements").select("id,title,content,created_at,updated_at").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-featured-prices.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SYMBOLS = {
  BTC: "BTCUSDT",
  ETH: "ETHUSDT",
  BNB: "BNBUSDT",
  SOL: "SOLUSDT",
  XRP: "XRPUSDT",
  DOGE: "DOGEUSDT"
};
var get_featured_prices_default = defineTool2({
  name: "get_featured_prices",
  title: "Get featured crypto prices",
  description: "Get current spot prices (USD) for featured cryptocurrencies from Binance. Supports BTC, ETH, BNB, SOL, XRP, DOGE.",
  inputSchema: {
    symbols: z2.array(z2.string()).optional().describe("Optional list of ticker symbols like ['BTC','ETH']. Defaults to all featured symbols.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ symbols }) => {
    const wanted = (symbols && symbols.length ? symbols : Object.keys(SYMBOLS)).map((s) => s.toUpperCase()).filter((s) => SYMBOLS[s]);
    const results = {};
    await Promise.all(
      wanted.map(async (s) => {
        try {
          const r = await fetch(`https://api.binance.com/api/v3/ticker/price?symbol=${SYMBOLS[s]}`);
          const j = await r.json();
          results[s] = j?.price ? Number(j.price) : null;
        } catch {
          results[s] = null;
        }
      })
    );
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { prices: results }
    };
  }
});

// src/lib/mcp/tools/get-yield-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var STRATEGIES = [
  { name: "Flexible Pool", apr: 0.5, minDeposit: 200, lockDays: 0 },
  { name: "Lock Staking", apr: 1.2, minDeposit: 200, lockDays: 30 },
  { name: "Legendary Capital", apr: 2.8, minDeposit: 200, lockDays: 90 }
];
function aprToApy(apr) {
  return Math.pow(1 + apr / 365, 365) - 1;
}
var get_yield_info_default = defineTool3({
  name: "get_yield_info",
  title: "Get USD.ONLINE yield strategies",
  description: "Get USD.ONLINE staking strategies with APR, daily-compounded APY, minimum deposit, and lock period.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = STRATEGIES.map((s) => ({
      ...s,
      apy: aprToApy(s.apr)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { strategies: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "usd-online-mcp",
  title: "USD.ONLINE MCP",
  version: "0.1.0",
  instructions: "Tools for USD.ONLINE, a BNB Smart Chain DeFi platform. Use `get_latest_news` for recent announcements, `get_featured_prices` for live crypto spot prices, and `get_yield_info` for staking strategies (APR, daily-compounded APY, lock period).",
  tools: [get_latest_news_default, get_featured_prices_default, get_yield_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
